### ISSUE TITLE
Setup unit tests

### ISSUE THREAD

**Issue by ayaMakh** [bobheadxi/calories#31]
- [Testing documentation](https://golang.org/pkg/testing/)
- [Mocking](https://stackoverflow.com/questions/19167970/mock-functions-in-go)

**Comment by bobheadxi** [comment]
- [tests in fakes](https://stackoverflow.com/questions/32425558/how-to-verify-if-a-specific-function-is-called-in-golang)
- [httptest](https://elithrar.github.io/article/testing-http-handlers-go/)
- [setup/teardown](https://stackoverflow.com/questions/23729790/how-can-i-do-test-setup-using-the-testing-package-in-go) OR:
- [tabledriventests](https://github.com/golang/go/wiki/TableDrivenTests):
> Typically, tests in go aren't written in the same style as other languages. Often, there's relatively fewer test functions, but each contains a table-driven set of test cases. See this article written by one of the Go team.
With a table-driven test, you simply put any setup code before the loop that executes the individual test-cases specified in the table, and put any cleanup code afterwards.
If you still have shared setup code between test functions, you can extract the shared setup code into a function, and use a sync.Once if it's important that it's executed exactly once (or as another answer suggests, use init(), but this has the disadvantage that the setup will be done even if the test cases aren't run (perhaps because you've limited the test cases by using go test -run <regexp>.)
I'd say if you think you need shared setup between different tests that gets executed exactly once you should have a think if you really need it, and if a table-driven test wouldn't be better. ([source](https://stackoverflow.com/a/23734015))
